version: '3.8'

services:
  app-cliente:
    build:
      context: ../mscliente
      dockerfile: Dockerfile
    container_name: ms-cliente-app
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SERVER_ADDRESS: "0.0.0.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banco_db
      SPRING_DATA_REDIS_HOST: redis-cache
    networks:
      - red-bancaria

  app-cuenta:
    build:
      context: ../mscuenta
      dockerfile: Dockerfile
    container_name: ms-cuenta-app
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SERVER_ADDRESS: "0.0.0.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banco_db
      SPRING_DATA_REDIS_HOST: redis-cache
    networks:
      - red-bancaria

networks:
  red-bancaria:
    external: true